"""empty message

Revision ID: 030823d49d63
Revises: 8314b2948343
Create Date: 2021-12-30 15:59:12.772126

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "030823d49d63"
down_revision = "8314b2948343"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "creators",
        sa.Column(
            "role",
            sa.Enum("ANONYMOUS_VIEWER", "SIGNED_CREATOR", name="roletype"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("creators", "role")
    # ### end Alembic commands ###
