"""empty message

Revision ID: 8314b2948343
Revises: 
Create Date: 2021-12-30 15:58:58.338954

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8314b2948343"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "creators",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "secrets",
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.Column(
            "create_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("secret", sa.String(), nullable=True),
        sa.Column("is_password_protected", sa.Boolean(), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["creator_id"], ["creators.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("secrets")
    op.drop_table("creators")
    # ### end Alembic commands ###
