"""empty message

Revision ID: 911f30290e65
Revises: 030823d49d63
Create Date: 2021-12-30 18:47:53.378570

"""

# revision identifiers, used by Alembic.
revision = "911f30290e65"
down_revision = "030823d49d63"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
